### ISSUE TITLE
Improve describe/context/it strings in tests

### ISSUE THREAD

**Issue by roback** [twingly/twingly-search-api-node#15]
For example [`it('with valid result containing non blogs' ...`](https://github.com/twingly/twingly-search-api-node/blob/0d99cc64a2697508fb685d5f3625fb94506c9ed6/test/test_parser.js#L193) does not read well. [In the Ruby client](https://github.com/twingly/twingly-search-api-ruby/blob/73d7cc5bb991762b5334cb8c00b19c41cbb57156/spec/parser_spec.rb#L193) that is a `context` that contains an `it` block instead.

There are more occurrences of this, other than the one mentioned above.

**Comment by walro** [comment]
@dentarg did a good job in #14 so I don't think all specs are bad
