### ISSUE TITLE
Replace nock-vcr

### ISSUE THREAD

**Issue by dentarg** [twingly/twingly-search-api-node#17]
Since early 2013, nothing has happened with [`nock-vcr`](https://github.com/carbonfive/nock-vcr). We should probably use something that is maintained.

Alternatives from https://github.com/vcr/vcr (ordered by star count, top has the most)

* https://github.com/flickr/yakbak
* https://github.com/linkedin/sepia
* https://github.com/elcuervo/vcr.js

**Comment by dentarg** [comment]
Nock also has recording: https://github.com/node-nock/nock#recording

**Comment by walro** [comment]
Also https://github.com/poetic/nock-vcr-recorder
