### ISSUE TITLE
Potential security vulnerability found in the marked dependency

### ISSUE THREAD

**Issue by walro** [twingly/twingly-search-api-node#22]
[marked](https://github.com/chjj/marked) is a dependency to [jsdoc](https://github.com/jsdoc3/jsdoc), unfortunately we cannot do anything until https://github.com/jsdoc3/jsdoc/issues/1489 has been taken care of.

**Comment by roback** [comment]
A temporary fix for this was made in https://github.com/twingly/twingly-search-api-node/pull/23

**Comment by walro** [comment]
It feels like upstream will never fix this... We could just close it as the fix we have in place is good enough. I have subscribed to the upstream issue so I will notice if something happens.

**Comment by roback** [comment]
:+1: Sure, why not. It's always possible to reopen this issue later.
